name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  reuse-lint:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run REUSE Compliance Check
        uses: https://github.com/fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6

  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install bun
        uses: https://github.com/oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: '24'
          package-manager-cache: false

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint backend
        run: bun run --cwd apps/backend lint

      - name: Lint frontend
        run: bun run --cwd apps/frontend lint

  test-building:
    name: Test Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install bun
        uses: https://github.com/oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: '24'
          package-manager-cache: false

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        env:
          DO_NOT_TRACK: 1
        run: bun run build
